/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package gra

import io.ktor.client.HttpClient
import io.ktor.client.features.json.JsonFeature
import io.ktor.client.request.get
import kotlinx.coroutines.Deferred
import kotlinx.coroutines.async
import kotlinx.coroutines.coroutineScope
import kotlinx.coroutines.runBlocking
import kotlin.system.measureTimeMillis

val client: HttpClient = HttpClient() {
    install(JsonFeature)
}

fun main(args: Array<String>): Unit = runBlocking<Unit> {
    runBlocking {
        val timeSequential = measureTimeMillis {
            displayPokemonsSequential()
        }
        
        val timeParallell = measureTimeMillis {
            displayPokemonsParallell()
        }

        println("It took $timeParallell ms to get pokemons in parallell")
        println("It took $timeSequential ms to get pokemons in sequence")
    }
    client.close()
}

data class Pokemon(val name: String)

suspend fun displayPokemonsParallell(): Unit = coroutineScope<Unit> {

    val firstDeferredPokemon: Deferred<Pokemon> =
        async { client.get<Pokemon>("https://pokeapi.co/api/v2/pokemon/ditto/") }

    val secondDeferredPokemon: Deferred<Pokemon> = async { client.get<Pokemon>("https://pokeapi.co/api/v2/pokemon/1/") }

    val firstPokemon: Pokemon = firstDeferredPokemon.await()
    val secondPokemon: Pokemon = secondDeferredPokemon.await()

    println(firstPokemon)
    println(secondPokemon)

}

suspend fun displayPokemonsSequential(): Unit = coroutineScope<Unit> {

    val firstPokemon: Pokemon = client.get<Pokemon>("https://pokeapi.co/api/v2/pokemon/ditto/")

    val secondPokemon: Pokemon = client.get<Pokemon>("https://pokeapi.co/api/v2/pokemon/1/")

    println(firstPokemon)
    println(secondPokemon)

}


