/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package gra

import io.ktor.client.HttpClient
import io.ktor.client.features.json.JsonFeature
import io.ktor.client.request.get
import kotlinx.coroutines.Deferred
import kotlinx.coroutines.async
import kotlinx.coroutines.coroutineScope
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking

fun main(args: Array<String>): Unit = runBlocking<Unit> {
    launch {
        displayPokemons()
    }
}

data class Pokemon(val name: String)

suspend fun displayPokemons(): Unit = coroutineScope<Unit> {

    val client: HttpClient = HttpClient() {
        install(JsonFeature)
    }

    val firstDeferredPokemon: Deferred<Pokemon> = async { client.get<Pokemon>("https://pokeapi.co/api/v2/pokemon/ditto/") }

    val secondDeferredPokemon: Deferred<Pokemon> = async { client.get<Pokemon>("https://pokeapi.co/api/v2/pokemon/1/") }

    val firstPokemon: Pokemon = firstDeferredPokemon.await()
    val secondPokemon: Pokemon = secondDeferredPokemon.await()

    println(firstPokemon)
    println(secondPokemon)

    client.close()
}


