/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package gra

import io.ktor.client.HttpClient
import io.ktor.client.features.json.JsonFeature
import io.ktor.client.request.get
import kotlinx.coroutines.Deferred
import kotlinx.coroutines.GlobalScope
import kotlinx.coroutines.async
import kotlinx.coroutines.coroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking

fun main(args: Array<String>) = runBlocking<Unit> {
    launch {
        requests()
    }
}

data class Pokemon(val name: String, val height: Int)

suspend fun requests() = coroutineScope<Unit> {

    val client = HttpClient() {
        install(JsonFeature)
    }

    val first: Deferred<Pokemon> = async { client.get<Pokemon>("https://pokeapi.co/api/v2/pokemon/ditto/") }

    val second: Deferred<Pokemon> = async { client.get<Pokemon>("https://pokeapi.co/api/v2/pokemon/1/") }

    println(first.await())
    println(second.await())

    client.close()
}


